[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.virtualenv"
]

[phases.install]
commands = [
  # Создаем виртуальное окружение в допустимой директории
  "python -m venv /tmp/venv",
  # Устанавливаем пакеты через venv
  "/tmp/venv/bin/pip install -r requirements.txt",
  
  # Копируем установленные пакеты в рабочую директорию
  "mkdir -p /app/.local-python",
  "cp -r /tmp/venv/lib/python3.10/site-packages/* /app/.local-python/"
]

[start]
cmd = "PYTHONPATH=/app/.local-python python bot.py"
