[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools"
]

[phases.install]
commands = [
  "python --version",
  "pip --version",
  "pip install -r requirements.txt --user"
]

[start]
cmd = "python bot.py"
