[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]  # Явно устанавливаем Python и pip

[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
